name: volkan

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check for dependency updates
        run: |
           mvn versions:display-property-updates versions:display-parent-updates -DgenerateBackupPoms=false \
            | grep '\->' \
            | awk -F ' ' '{if ($2 != $4) print $0}' > dependency-updates.txt

      - name: Extract dependency updates
        id: extract-updates
        run: |
          echo "::set-output name=updates::$(grep -c ' -> ' dependency-updates.txt)"

      - name: Comment on pull request
        if: ${{ steps.extract-updates.outputs.updates > 0 }}
        run: |
          echo "❌ WARNING: The following dependencies or microservices have updates available:"
          cat dependency-updates.txt

      - name: Comment on pull request (no updates found)
        if: ${{ steps.extract-updates.outputs.updates == 0 }}
        run: |
          echo "✅ No dependency updates found."
